export const FETCH_IMAGES = 'FETCH_IMAGES'
export const SET_FETCH_IMAGES_LOADING = 'SET_FETCH_IMAGES_LOADING'
export const SET_FETCH_IMAGES_SUCCESS = 'SET_FETCH_IMAGES_SUCCESS'
export const SET_FETCH_IMAGES_ERROR = 'SET_FETCH_IMAGES_ERROR'

export const SELECT_IMAGE = 'SELECT_IMAGE'